### ISSUE TITLE
报sql错误，已找到问题所在，但不知作者为何这样写，特此请教

### ISSUE THREAD

**Issue by inory121** [xunlu129/teriteri-client#36]
![image](https://github.com/user-attachments/assets/5c1696a2-6ce3-4ac5-8ce6-9cbde9d2f520)
![image](https://github.com/user-attachments/assets/e8116d7d-a072-4540-bbd6-dbc81849d833)

在视频页 http://localhost:8787/video/XX 会报这个错，注释掉VideoDetail.vue这段就没报错了，不知道作者的项目跑起来有没有这个问题，还是我哪里没设置好才有这个
![image](https://github.com/user-attachments/assets/ddc086ed-239c-4612-9961-0f3a3ddc2590)

这里不是很清楚为什么调用两次"/video/cumulative/visitor"这个接口，调用两次的话经过两次去重
```List<Map<String, Object>> videoList = videoService.getVideosWithDataByIds(idSet, 1, 10);```
这里的idSet变成空的了

**Comment by xunlu129** [comment]
前面有判定 `if (!idSet.isEmpty())` 的吧，正常来说 idSet 变成空时不会执行 `videoService.getVideosWithDataByIds` 的喔，为啥你这里执行了？你 debug 确定一下真是这里的问题？

**Comment by inory121** [comment]
好吧是我的问题，我4月多整的一直没更新，我看5月多已经修复了这部分代码，😂。顺便问一下大佬找着工作了吗，我也快毕业要实习了，但我是专升本上的本科，最近也有点焦虑找工作会不会有学历歧视😭

**Comment by xunlu129** [comment]
找到啦，我也投了好久，我自己也不是一流大学，专业也不是计算机，但好在硬实力过关，第一次面试就拿到offer了，只能说还是有公司不看学历的哈哈
