### ISSUE TITLE
请教一下如何用nginx做转发

### ISSUE THREAD

**Issue by semanym** [xunlu129/teriteri-client#38]
想打包了然后用nginx做转发，不管咋配置好像请求都失效，请问有nginx.conf可以参考吗

**Comment by xunlu129** [comment]
server
{
    listen 80;
    server_name 你的域名或者服务ip;
    index index.php index.html index.htm default.php default.htm default.html;
    root 打包的index.html的路径;

    location / {
      try_files $uri $uri/ /index.html;
    }

    location /api {
        rewrite  ^.+api/?(.*)$ /$1 break;
        proxy_pass  http://localhost:7070;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    #禁止访问的文件或目录
    location ~ ^/(\.user.ini|\.htaccess|\.git|\.env|\.svn|\.project|LICENSE|README.md)
    {
        return 404;
    }

    #一键申请SSL证书验证目录相关设置
    location ~ \.well-known{
        allow all;
    }

    #禁止在证书验证目录放入敏感文件
    if ( $uri ~ "^/\.well-known/.*\.(php|jsp|py|js|css|lua|ts|go|zip|tar\.gz|rar|7z|sql|bak)$" ) {
        return 403;
    }
}

**Comment by semanym** [comment]
感谢
